USE PR
DECLARE
@TopRate money, @NewHire date, @TotEmps int
SET @TopRate = (SELECT MAX(PAYRATE) FROM WORK)
SET @NewHire = (SELECT MAX(HIREDATE) FROM EMPDATA)
SET @TotEmps = (SELECT COUNT(EMPID) FROM EMPDATA WHERE TERMDATE IS NULL)

BEGIN
PRINT 'THE TOP PAYRATE FOR THE COMPANY IS $' + CONVERT(VARCHAR, @TOPRATE)
PRINT 'THE NEWEST EMPLOYEE FOR THE COMPANY STARTED ON ' + CONVERT(VARCHAR, @NEWHIRE)
PRINT 'THERE ARE CURRENTLY ' + CONVERT(VARCHAR, @TOTEMPS) + ' EMPLOYEES WORKING FOR THE COMPANY.'
END