
USE PR
DECLARE @TotHours INT, @TotEmps int, @HolHours INT, @RegHours INT, @OTHours INT

SET @TotHours = (SELECT SUM(workhours) FROM Hours where PPID IN (SELECT max(ppid) FROM HOURS))
SET @TotEmps = (SELECT COUNT(EmpId) FROM empdata where termdate is null)
SET @HOLHOURS = (SELECT SUM(HolHours) FROM HOURS WHERE PPID IN (SELECT max(ppid) FROM HOURS))
SET @REGHOURS = @TOTEMPS * 32
BEGIN
IF @HOLHOURS > 0
BEGIN
PRINT 'HOLIDAY HOURS ARE GREATER THAN 0, YOURE GONNA WANNA SEE THIS'
IF @REGHOURS > @TOTHOURS
BEGIN
SET @REGHOURS = @TOTHOURS
SET @OTHours = 0
PRINT 'TOTAL REGULAR HOURS FOR THE WEEK: ' + CONVERT(VARCHAR, @REGHOURS)
PRINT 'TOTAL HOLIDAY HOURS FOR THE WEEK: ' + CONVERT(VARCHAR, @HOLHOURS)
PRINT 'TOTAL OT HOURS FOR THE WEEK: ' + CONVERT(VARCHAR, @OTHOURS)
END
ELSE
BEGIN
SET @OTHOURS = @tothours - @reghours
PRINT 'TOTAL REGULAR HOURS FOR THE WEEK: ' + CONVERT(VARCHAR, @REGHOURS)
PRINT 'TOTAL HOLIDAY HOURS FOR THE WEEK: ' + CONVERT(VARCHAR, @HOLHOURS)
PRINT 'TOTAL OT HOURS FOR THE WEEK: ' + CONVERT(VARCHAR, @OTHOURS)
END
END
END